// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 3
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EFCoreReversePocoDemo.App
{

    // Hotel
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class Hotel
    {
        public int HotelId { get; set; } // HotelId (Primary key)
        public string HotelName { get; set; } // HotelName (length: 200)
        public string HotelDescription { get; set; } // HotelDescription (length: 500)
        public string City { get; set; } // City (length: 100)
        public System.DateTime EstablishedDate { get; set; } // EstablishedDate

        // Reverse navigation

        /// <summary>
        /// Child Rooms where [Room].[HotelId] point to this entity (FK_Room_Hotel)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Room> Rooms { get; set; } // Room.FK_Room_Hotel

        public Hotel()
        {
            Rooms = new System.Collections.Generic.List<Room>();
        }
    }

}
// </auto-generated>
