// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 3
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EFCoreReversePocoDemo.App
{

    // Hotel
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class HotelConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Hotel>
    {
        public HotelConfiguration()
            : this("dbo")
        {
        }

        public HotelConfiguration(string schema)
        {
            ToTable("Hotel", schema);
            HasKey(x => x.HotelId);

            Property(x => x.HotelId).HasColumnName(@"HotelId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.HotelName).HasColumnName(@"HotelName").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(200);
            Property(x => x.HotelDescription).HasColumnName(@"HotelDescription").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(500);
            Property(x => x.City).HasColumnName(@"City").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(100);
            Property(x => x.EstablishedDate).HasColumnName(@"EstablishedDate").HasColumnType("datetime").IsRequired();
        }
    }

}
// </auto-generated>
