// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 3
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EFCoreReversePocoDemo.App
{

    // Room
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class Room
    {
        public int RoomId { get; set; } // RoomId (Primary key)
        public int HotelId { get; set; } // HotelId
        public string RoomNumber { get; set; } // RoomNumber (length: 20)
        public decimal Price { get; set; } // Price
        public bool IsAvaliable { get; set; } // IsAvaliable
        public string RoomDescription { get; set; } // RoomDescription (length: 200)

        // Foreign keys

        /// <summary>
        /// Parent Hotel pointed by [Room].([HotelId]) (FK_Room_Hotel)
        /// </summary>
        public virtual Hotel Hotel { get; set; } // FK_Room_Hotel
    }

}
// </auto-generated>
