// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 3
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace EFCoreReversePocoDemo.App
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.37.4.0")]
    public class SearchHotelReturnModel
    {
        public System.Int32 HotelId { get; set; }
        public System.String HotelName { get; set; }
        public System.String HotelDescription { get; set; }
        public System.String City { get; set; }
        public System.DateTime EstablishedDate { get; set; }
        public System.String RoomNumber { get; set; }
        public System.String RoomDescription { get; set; }
        public System.Decimal Price { get; set; }
        public System.Boolean IsAvaliable { get; set; }
    }

}
// </auto-generated>
